### ISSUE TITLE
Default communication

### ISSUE THREAD

**Issue by latapata** [BoschSensortec/BMA2x2_driver#1]
I am developing driver for this Sensor in contiki operating system. I wanted to know If anybody has already integrated the sensor drivers into coniki os.

My second uestion would be what is the basic communication interface spi or i2c. 

If we have to activate spi interface what are the changes required to be made in the driver.

**Comment by BoschSensortec** [comment]
For using SPI interface, you need to have SPI read and write functions which are specific to your platform and it should be mapped to the sensor driver.
Please refer bma2x2_support.c file. which contains the reference for SPI bus read and write functions.
Thank you.

**Comment by BoschSensortec** [comment]
There is no input for this feedback hence we are closing this issue. Please reopen if you need any information.
