### ISSUE TITLE
Win upd driver - rotation wrong (90 deg offset)

### ISSUE THREAD

**Issue by madmax911** [BoschSensortec/BMA2x2_driver#2]
Hi,

I have a Winbook TW700 and I recently installed the following driver via win updates:
"Bosch - Location Sensor - BMA2x2 accelerometer"
It caused my screen to rotate wrong - it was 90 degrees off.  I ended up rolling back the driver but I just thought you should know.  I went to try and find the item number on windows update but they did not provide one.  I'll try and investigate more into this later.

**Comment by BoschSensortec** [comment]
Can you provide more information for the Windows update?  Which platform do you used? 

Please pay attention to the axis remapping setting compare to original drivers and the drivers you modified.

**Comment by madmax911** [comment]
Win 8.1 Core 32-bit.

Date: Wed, 15 Apr 2015 22:22:50 -0700

**Comment by madmax911** [comment]
To be clear, it was an optional driver that was pushed out by Microsoft update which I did choose to install but I did so believing that MS would not release a driver that would break things.  I'm not a driver dev guy just letting you know this in case you get a few emails from hardware vendors and/or end users.

Date: Wed, 15 Apr 2015 22:22:50 -0700

**Comment by Stonent** [comment]
I'm seeing the same thing with an RCA Cambio w101 v2 tablet.  ACPI\BMA250E\1.  The driver is "Bosch Corporation 11/12/2015 16.54.647 Microsoft Windows Hardware Compatibility Publisher"

**Comment by ShinSCDL** [comment]
I also have the same problem with the Cambio w101 v2 tablet, but I have the 9/23/2014   15.5.56.9 version of the driver. I also have the problem of the screen turning 180 degrees when I dock it to the keyboard. While I am using the tablet it seems to work fine.

**Comment by BoschSensortec** [comment]
Please contact Microsoft since this is an Windows driver update issue.
