### ISSUE TITLE
Windows 10 Home screen 180-degree rotated

### ISSUE THREAD

**Issue by alexlui** [BoschSensortec/BMA2x2_driver#4]
The Windows screen is 180-degree rotated (upside down) after the driver updated to 16.54.4.647 from Windows Update, whatever portrait or landscape. My tablet is Chuwi Vi8 with Bosch BMA250E (ACPI\BMA250E).

**Comment by BoschSensortec** [comment]
Kindly contact the OEM(Chuwi) customer care. Email address is as below 
service@chuwi.com.cn 

The issue shall be due to axis remapping.

**Comment by alexlui** [comment]
The original driver comes from the box works without problem, only the one from Windows Update gets this problem.

**Comment by BoschSensortec** [comment]
We are contacting Windows for thisissue. 
It should be Windows update issue.

**Comment by tiiongtsu** [comment]
device : chuwi Hi8 
When update system to win10 1511, screen rotate doesn't  work properly. 
When the system booted, screen rotate doesn't work immediately,it need a few minites then sceen rotate begin to work .

**Comment by BoschSensortec** [comment]
This issue is communicated and confirmed with Microsoft.
Please contact Microsoft for further help on this issue.
Thank you
