### ISSUE TITLE
This Driver for windows 8.1

### ISSUE THREAD

**Issue by EibarD** [BoschSensortec/BMA2x2_driver#6]
Hi i need to reinstall this driver for my winbook tw700 (windows8.1), but i need the .inf file which  is not provided on the zip download. Where can i find this file?. If is not available, what can i do to install the .c file?

**Comment by BoschSensortec** [comment]
Thanks for your feedback. 
Windows driver related code is maintained by Microsoft. We will release our driver and it will be published by Microsoft with whole package.
So for any issue related to Windows driver, please contact Microsoft first.
